server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://dpg-d4bkfgpr0fns73fgurp0-a:5432/fecredit_db
    username: fecredit_db_user
    password: kpM4rmW2SVpWd5LDKwSZFytxZco0JBfG

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
